'use strict';let e=[[1,[0,0,.1],[[1,0,.4]],[]],[2,[2,0,.1],[[1,0,.3],[3,0,.4]],[]],[3,[4,0,.1],[[.75,0,.15],[.75,.5,.1]],[]],[4,[1.5,.5,.15],[],[[1.5,0,.2,7E-4]]],[4,[2.5,0,.1],[[1.5,0,.4],[1.5,.6,.15],[1.5,-.6,.15]],[]],[3,[3,0,.1],[[1,.1,.15],[2,0,.1],[3,0,.15],[4,-.1,.15],[5,0,.1]],[]],[5,[6,0,.1],[[1,0,.15],[2,.1,.1],[3.5,0,.5,100],[5,-.1,.15],[6,0,.1]],[]],[2,[7,0,.1],[[.8,0,.2],[0,1,.3],[1,1,.3]],[]],[2,[1,1.5,.1],[[.3,.2,.05,10],[.5,.52,.05,10],[.35,.48,.03,10],[.55,.3,.05,10],[.4,.1,.08,10],
[.6,.6,.05,10],[.5,.94,.06,10],[.6,.86,.05,10],[.8,.7,.04,10],[.7,.5,.05,10],[.5,-.2,.2,40],[.2,.94,.15,30],[0,.7,.08,20],[-.2,.5,.15,30]],[]],[1.5,[1,.9,.1],[[1,0,.2],[1.5,.2,.15],[2,.22,.18],[2.5,.25,.1,40],[.5,.5,.1,40],[1,.7,.18],[1.5,.9,.2],[2,.98,.22]],[]],[4.5,[3,.6,.1],[[2.5,1.5,.2]],[[1.5,0,.2,7E-4]]],[4,[3,1.5,.1],[],[]],[3,[1,-3,.1],[[1,0,.2],[2,-.15,.2],[3,.15,.2]],[]],[5,[4,0,.1],[[1,0,.2],[3,0,.15]],[[2,0,.1,1E-4]]],[3,[4,0,.1],[[.5,0,.15],[1,.5,.15],[1,-.5,.15],[1.5,0,.15],[2,.5,.15],
[2,-.5,.15],[2.5,0,.15]],[]],[3,[3,0,.1],[],[]],[3,[2,0,.1],[[.6,.3,.08,20],[2.1,1.2,.08,20],[2.7,-.6,.08,20],[2.9,-.2,.08,20],[2.2,.1,.08,20],[2.5,-.5,.08,20],[.2,1.2,.08,20],[1.1,-.1,.08,20],[2.4,0,.08,20],[1,-.3,.08,20],[2.3,.9,.08,20],[0,1.1,.08,20],[1.1,-.8,.08,20],[1.6,1.6,.08,20],[2.3,-.7,.08,20],[2.7,.6,.08,20],[2.2,.4,.08,20],[2.7,.3,.08,20],[.3,-.1,.08,20],[1.3,1.3,.08,20]],[]],[3,[3.5,.5,.1],[],[]],[9,[3,.5,.1],[[1,-.5,.15],[1,-.25,.05,20],[1,0,.15],[1,.25,.05,20],[1,.5,.15]],[[1,-.9,.15,
3E-4],[1,.9,.15,3E-4]]],[9,[2,0,.3],[],[]]];function aa(a,c){var b=ba,d=Math.sin(b);b=Math.cos(b);return Math.atan2(d+(Math.sin(a)-d)*c,b+(Math.cos(a)-b)*c)}function g(a,c,b){return a<c?c:a>b?b:a}function da(){let a=g((Math.hypot(r,t)-10)/15,0,1);return a*a*(3-2*a)}function u(a){return()=>{let c=a+=1831565813;c=Math.imul(c^c>>>15,c|1);c^=c+Math.imul(c^c>>>7,c|61);return((c^c>>>14)>>>0)/2**32}}let v,w,x,ea,fa,y;
function ha(){v=new AudioContext;w=v.createGain();w.gain.value=.5;x=v.createBiquadFilter();x.type="highshelf";x.frequency.value=200;x.gain.value=0;x.connect(w);w.connect(v.destination);ea=v.createBuffer(1,v.sampleRate,v.sampleRate);var a=ea.getChannelData(0);let c=u(0);a.set(a.map(()=>2*c()-1));fa=v.createPeriodicWave(new Float32Array([0,0,1,.1,-.4,0,1,0,-.9,.1,.4,-.1,0,.2,-.1,.1,0,0,.1,.1,0,0,0,0,0,.1,.2,-.2,-.3,.1,.1,-.2,0,0,.1,0,-.1,-.4,.2,.4,.1,.3,.3,0,0,-.2,.1,-.1,-.1,-.3,.1,-.1,0,0,.1,.1,0,
.1,.1,-.2,0,-.1,-.1,0,0,-.1,-.2,0,.1,0,-.1,.1,-.1,0,0,-.1,-.1,0,-.1,-.1,-.1]),new Float32Array([0,0,1,-.1,.2,0,-.3,.1,-.5,-.8,0,0,-.4,0,-.3,-.1,0,0,0,0,.1,.1,0,-.1,0,.1,-.4,.1,-.1,-.2,0,0,-.1,0,.1,-.2,0,-.2,0,-.2,0,.4,0,-.4,.3,.1,0,-.1,.2,-.1,.2,-.1,-.2,-.2,.2,0,-.2,.1,-.2,-.2,0,0,0,0,.1,-.1,-.1,0,.1,0,0,.1,0,0,0,0,0,0,0,0,0]));ia();a=z();y=v.createGain();let b=v.createBiquadFilter();y.gain.value=0;b.type="bandpass";b.frequency.value=250;b.Q.value=5;a.connect(b);b.connect(y);y.connect(x);a.start()}
function z(){let a=v.createBufferSource();a.buffer=ea;a.loop=!0;return a}
function A(a,c,b,d,k,f,m){let n=v.createOscillator(),h=v.createGain(),q=v.createBiquadFilter();n.frequency.value=a;h.gain.value=0;let l=b;h.gain.linearRampToValueAtTime(0,l);l+=.01;h.gain.linearRampToValueAtTime(c,l);l+=d;h.gain.linearRampToValueAtTime(c,l);l+=k;h.gain.linearRampToValueAtTime(0,l);q.type="bandpass";q.Q.value=f;q.frequency.value=a;n.connect(h);h.connect(q);q.connect(x);"string"===typeof m?n.type=m:n.setPeriodicWave(m);n.start(b);n.stop(l)}
function B(a,c,b,d,k,f,m=.01,n=.1,h=0){let q=v.createGain(),l=v.createBiquadFilter();q.gain.value=0;let p=c;q.gain.linearRampToValueAtTime(0,p);p+=m;q.gain.linearRampToValueAtTime(a,p);p+=h;q.gain.linearRampToValueAtTime(a,p);p+=n;q.gain.linearRampToValueAtTime(0,p);l.type=d?"bandpass":"allpass";l.frequency.value=k;l.Q.value=f;b.connect(q);q.connect(l);l.connect(x);b.start(c);b.stop(p)}function ja(a){B(.2,a,z(),!0,1E4,2)}function ka(a){B(.2,a,z(),!0,1E4,1,.02,.06)}let la=0;
function ia(){function a(q,l,p,C){l=2**(Math.log2(440)+l-4+(p-9)/12);A(l,.1,q,C,.05,.02,fa);A(l,.1/1.5,q+.25,C,.05,.5,fa);A(l,.05,q+.5,C,.05,1,fa)}let c=v.currentTime+.1,b=!0,d=!1,k=!1,f=ja,m=u(0),n,h=()=>{let q=(v.currentTime+9)/8;for(;la<q;){let C=c+8*la;0===la%2&&(n=u(10*m()|0));++la;for(var l=0;16>l;++l){if(b){var p=C+.5*l;let ca=v.createOscillator();ca.frequency.value=250;ca.frequency.linearRampToValueAtTime(250,p+.01+0);ca.frequency.linearRampToValueAtTime(50,p+.03+0);B(.3,p+0,ca,!1,0,0,.01,
.1,.05)}k&&f(C+.5*(l+.5))}for(p=0;8>p;++p)d&&B(.1,C+p+.5,z(),!0,1800,1,.01,.05,.07);!b||.1>m()?b=!b:!d||.1>m()?d=!d:!k||.1>m()?k=!k:.2>m()&&(f=f===ja?ka:ja);p=[[0,2,4,7,9],[2,4,7,9,12],[4,7,9,12,14]];p=p[n()*p.length|0];for(l=0;16>l;++l).5>n()?a(C+.5*l,2,p[n()*p.length|0]-10,.25*(.5>n()?1:.5)):(a(C+.5*l,2,p[n()*p.length|0]-10,.125),a(C+.25*(2*l+1),2,p[n()*p.length|0]-10,.125))}};h();setInterval(h,1111)}
function ma(a,c,b){a.i.width=c;a.i.height=b;a.g.viewport(0,0,c,b);a.g.uniform4f(a.h.uScreenSize,c,b,1/c,1/b);a.g.uniform2f(a.h.uAspect,c/b,b/c)}function na(a){a.g.uniform1f(a.h.uTime,.001*performance.now());a.g.drawArrays(a.g.TRIANGLE_STRIP,0,a.v.length/2)}class oa{constructor(a,...c){c.push("uTime","uScreenSize","uAspect");var b=`#version 300 es
precision highp float;uniform float uTime;uniform vec4 uScreenSize;uniform vec2 uAspect;in vec4 vPixelCoord;out vec4 f;${a}void main(){vec4 c;mainImage(c, vPixelCoord.xy);f = c;}`;a=this.g=(this.i=document.createElement("canvas")).getContext("webgl2");var d=a.createShader(a.VERTEX_SHADER),k=a.createShader(a.FRAGMENT_SHADER);a.shaderSource(d,"#version 300 es\nin vec2 aVertexPosition;uniform vec4 uScreenSize;uniform float uTime;out vec4 vPixelCoord;void main(){vec2 a=(aVertexPosition+vec2(1.))*.5;vPixelCoord=vec4(a,a*uScreenSize.xy);gl_Position=vec4(aVertexPosition,0.,1.);}");
a.shaderSource(k,b);a.compileShader(d);a.compileShader(k);b=a.createProgram();a.attachShader(b,d);a.attachShader(b,k);a.linkProgram(b);a.useProgram(b);d=a.createBuffer();this.v=new Float32Array([-1,-1,1,-1,-1,1,1,1]);k=a.getAttribLocation(b,"aVertexPosition");a.bindBuffer(a.ARRAY_BUFFER,d);a.enableVertexAttribArray(k);a.vertexAttribPointer(k,2,a.FLOAT,!1,0,0);a.bufferData(a.ARRAY_BUFFER,this.v,a.STATIC_DRAW);this.h={};for(const f of c)this.h[f]=a.getUniformLocation(b,f)}}let pa;
const D=new oa("uniform vec2 offset;uniform float globalZoom;uniform int numBlackHoles;uniform vec4 blackHoleData[6];float noise(in float x){float i=floor(x),f=fract(x),s=sign(fract(x*.5)-.5),k=fract(i*.1731);return s*f*(f-1.)*((16.*k-4.)*f*(f-1.)-1.);}void mainImage(out vec4 fragColor, in vec2 fragCoord){vec2 uv=(fragCoord-.5)/4./globalZoom;uv.x*=uAspect.x;vec2 offsetLocal=offset/8.;vec3 from=vec3(offsetLocal,-11.11);float light=1.,blackHoleOutlineGlow=0.;vec2 originalUv = uv;vec3 blackHoleOutlineGlowColor=vec3(1,.3,0);for (int i=0;i<numBlackHoles;++i){vec4 data=blackHoleData[i]/4.;vec2 pos=data.xy/2.-offsetLocal;pos*=2.;float radius=data.z,effectRadius=data.w,currentDist=distance(pos,originalUv);vec2 warp=normalize(pos-originalUv)*pow(currentDist,-2.)*effectRadius;uv+=warp;light*=clamp((currentDist-radius)*200.,0.,1.);blackHoleOutlineGlow+=2./(abs(currentDist-radius)*1e3);}vec3 dir=vec3(uv*5.,1);mat2 rot1=mat2(cos(1.),sin(1.),-sin(1.),cos(1.));mat2 rot2=mat2(cos(2.5),sin(2.5),-sin(2.5),cos(2.5));dir.xz*=rot1;dir.xy*=rot2;from.xz*=rot1;from.xy*=rot2;float s=.5,fade=.9;vec3 v=vec3(-1);for (int r=0;r<15;++r){vec3 p=from+s*dir*.5;p=abs(vec3(.85)-mod(p,vec3(1.7)));float a=0.;for (int i=0;i<15;++i){p=abs(p)/dot(p,p)-0.56;float D=length(p);float fade2=5./(float(i)*2.+20.);a+=mix(min(15.,D),D,fade2);}fade*=clamp(5./float(r+1),0.,1.);a=pow(a,3.2+noise(uTime*.01)*.1);v+=fade-.2+vec3(s*s*s*s,s*s,s)*a*8e-4*fade;fade*=.5-noise(uTime*.01)*.1;s+=.25;}vec3 rgb=pow(v*.01*sqrt(s),vec3(1.5))*1.5;rgb.r*=.4+noise(uTime*.02+1.23)*.3;rgb=clamp(rgb,vec3(0),vec3(1))*.8;rgb+=blackHoleOutlineGlowColor*clamp(blackHoleOutlineGlow,0.,1.)*.6;rgb=mix(vec3(0),rgb,light);fragColor=vec4(rgb,1.);}","offset",
"globalZoom","numBlackHoles","blackHoleData");document.body.appendChild(D.i);D.i.style.position="absolute";D.i.style.zIndex=-3;function qa(){ma(D,window.innerWidth,window.innerHeight)}qa();window.addEventListener("resize",qa);requestAnimationFrame(ra);function ra(){requestAnimationFrame(ra);D.g.uniform2f(D.h.offset,E.position.x,E.position.y);D.g.uniform1f(D.h.globalZoom,F);na(D)}let G=[9E9,9E9,0,0,9E9,9E9,0,0,9E9,9E9,0,0,9E9,9E9,0,0,9E9,9E9,0,0,9E9,9E9,0,0];
pa=(a,c,b,d,k)=>{a*=4;G[a]=c;G[a+1]=b;G[a+2]=d;G[a+3]=k;D.g.uniform4fv(D.h.blackHoleData,G)};D.g.uniform4fv(D.h.blackHoleData,G);let F=1;function sa(){var a=H;a.element.style.left=window.innerWidth/2+"px";a.element.style.top=window.innerHeight/2+"px";a.element.style.transform=`scale(${F}) translate(${-a.g.position.x*window.innerHeight}px, ${a.g.position.y*window.innerHeight}px)`;a.h.forEach(c=>c.l())}
class ta{constructor(){this.g={position:{x:0,y:0}};this.h=new Set;this.element=document.body.appendChild(document.createElement("div"));this.element.id="scene"}add(a){this.h.add(a);this.element.appendChild(a.element)}remove(a){this.h.delete(a);this.element.removeChild(a.element)}}
class ua{constructor(a=!0){this.element=document.createElement("div");this.s=[];this.position={x:0,y:0};this.g=0;this.h=1;a&&this.l()}l(){this.element.style.transform=`translate(${this.position.x*window.innerHeight}px, ${-this.position.y*window.innerHeight}px) rotate(${-this.g}rad) scale(${this.h})`;this.s.forEach(a=>a())}}
class va extends ua{constructor(){super();this.j=.025;let a=this.element.appendChild(document.getElementById("ship"));this.s.push(()=>{a.style.width=`${.05*1.5*window.innerHeight}px`;a.style.height=`${.05*1.5*window.innerHeight}px`});this.element.style.zIndex=1;this.l()}}
class wa extends ua{constructor(){super();this.element.className="arrow";let a=this.element.appendChild(document.createElement("div")).appendChild(document.getElementById("arrow"));a.style.transform="translate(-50%, -50%)";this.s.push(()=>{a.setAttributeNS(null,"width",`${.1*window.innerHeight}px`);a.setAttributeNS(null,"height",`${.1*window.innerHeight}px`)});this.element.style.zIndex=2;this.element.style.opacity=0;this.l()}}
class xa extends ua{constructor(a,c,b){super();this.element.appendChild(a);a.style.transform="translate(-50%, -50%)";this.D=!0;this.o=0;this.B=this.A=1;this.m=b;this.i=c(this);this.s.push(()=>{a.style.width=window.innerHeight*this.A+"px";a.style.height=window.innerHeight*this.B+"px"});this.i(0)}}function ya(a=1,c){var b=za;for(let d=0;d<a;++d){let k=new xa(b.i.cloneNode(!0),b.v,c);b.h.add(k);b.g.add(k)}}function Aa(){var a=za,c=I;for(let b of a.g)b.o+=c,b.i(c),b.D||(a.g.delete(b),a.h.remove(b))}
class Ba{constructor(a){var c=Ca;this.h=H;this.i=c;this.g=new Set;this.v=a}}
const J=new oa("uniform vec3 colorData[4];uniform int numColors;uniform float planetRadius;uniform float seed;uniform float noiseScale;vec3 hash3(vec3 p){p = vec3(dot(p,vec3(127.1,311.7,74.7)),dot(p,vec3(269.5,183.3,246.1)),dot(p,vec3(113.5,271.9,124.6)));return 2.*fract(sin(p)*43758.5453123)-1.;}float simplexNoise(vec3 p){const float K2=1./6.;vec3 i=floor(p+(p.x+p.y+p.z)/3.),d0=p-(i-(i.x+i.y+i.z)*K2),e=step(vec3(0),d0-d0.yzx),i1=e*(1.-e.zxy),i2=1.-e.zxy*(1.-e),d1=d0-(i1-1.*K2),d2=d0-(i2-2.*K2),d3=d0-(1.-3.*K2);vec4 h=max(.6-vec4(dot(d0,d0),dot(d1,d1),dot(d2,d2),dot(d3,d3)),0.),n=h*h*h*h*vec4(dot(d0,hash3(i)),dot(d1,hash3(i+i1)),dot(d2,hash3(i+i2)),dot(d3,hash3(i+1.)));return dot(vec4(31.316),n);}vec3 hsv2rgb(vec3 c){vec4 K=vec4(1,2./3.,1./3.,3);vec3 p=abs(fract(c.xxx+K.xyz)*6.-K.www);return c.z*mix(K.xxx,clamp(p-K.xxx,0.,1.),c.y);}void mainImage(out vec4 fragColor, in vec2 fragCoord){vec2 uv=(fragCoord-.5)*(planetRadius+.004)*2.;float currentPlanetDistance=length(uv);vec3 originalPlanetColor=hsv2rgb(colorData[0]);vec2 planetDir=uv/planetRadius;float len=clamp(length(planetDir),0.,1.),z=sqrt(1.-len*len);vec3 normal=vec3(planetDir,z),planetColor=vec3(0);float mul=1.,scale=planetRadius*50.*noiseScale,mulmul=2.5;for (int i=0;i<numColors;++i){planetColor+=smoothstep(-1.2,1.6,simplexNoise(vec3(seed)+normal*mul*scale))/mul*hsv2rgb(colorData[i]);mul*=mulmul;}float side=smoothstep(0.,1.,(currentPlanetDistance-planetRadius)*1e3);planetColor*=mix(.2,1.,pow(dot(normal,vec3(0,0,1)),2.));float glowIntensity=smoothstep(1.,0.,(currentPlanetDistance-planetRadius+.001)*2e2);vec3 rgb=glowIntensity*originalPlanetColor*.4;rgb=mix(planetColor,rgb,smoothstep(0.,1.,(currentPlanetDistance-planetRadius)*1e3));fragColor=vec4(rgb,glowIntensity);}","numColors",
"colorData","planetRadius","seed","noiseScale"),Da=[];function Ea(){let a;null==(a=Da.shift())||a.call();requestAnimationFrame(Ea)}requestAnimationFrame(Ea);
class Fa extends ua{constructor(a,c,b,d,k,f,m){super(!1);this.element.style.zIndex=-1;this.element.classList.add("planet");this.j=a;this.F=f;this.u=!1;this.level=m;this.G=c;if(f){let h=this.element.appendChild(document.createElement("div"));h.classList.add("pulse");h.style.borderRadius="50%";h.style.background="cyan";this.s.push(()=>{h.style.width=2*a*window.innerHeight+"px";h.style.height=2*a*window.innerHeight+"px"})}this.C=!0;const n=this.element.appendChild(new Image);this.H=()=>{this.C&&(this.C=
!1,Da.push(()=>{const h=window.innerHeight*a*2;ma(J,h,h);J.g.uniform1i(J.h.numColors,d.length);J.g.uniform3fv(J.h.colorData,d.flat());J.g.uniform1f(J.h.planetRadius,a/2);J.g.uniform1f(J.h.seed,b);J.g.uniform1f(J.h.noiseScale,k);na(J);n.src=J.i.toDataURL()}))};n.style.transform="translate(-50%, -50%)";window.addEventListener("resize",()=>this.C=!0)}l(){super.l();this.H()}}let K=!1,Ga=!1,Ha=!1;window.addEventListener("keydown",a=>{K||(K=" "===a.key);Ga=K&&!a.repeat;Ha||(Ha="Enter"===a.key&&!a.repeat)});
window.addEventListener("keyup",a=>{K&&(K=" "!==a.key)});let H=new ta,E=H.g,Ca=document.createElement("div");Ca.style.borderRadius="50%";Ca.style.background="radial-gradient(#ff6, #f52 30%, #0006 50%, #0000 80%)";
let za=new Ba(a=>{a.element.style.filter=`brightness(${Math.random()+.5})`;let c=.5*Math.random()+.5,b,d=null!=(b=a.m.angle)?b:Math.random()*Math.PI*2,k;a.A=null!=(k=a.m.A)?k:.03;let f;a.B=null!=(f=a.m.B)?f:.03;let m,n=null!=(m=a.m.speed)?m:.1*Math.random()+.2;a.position.x=a.m.x;a.position.y=a.m.y;return h=>{let q=n*(1-(1-(1-a.o/c)**2)),l=Math.sin(d)*q;a.position.x+=h*Math.cos(d)*q;a.position.y+=h*l;a.element.style.opacity=Math.sin((1-a.o/c)*Math.PI/2)/2;a.D=1>a.o/c}});const Ia=[[.55,1,2.5]];
D.g.uniform1i(D.h.numBlackHoles,6);let L=[],M=[],Ja,Ka,N=(null!=(Ka=+window.localStorage.getItem("kimbatt-js13k-2021"))?Ka:0)%(e.length-1);for(let a=1;a<e.length;++a){e[a][1][0]+=e[a-1][1][0];e[a][1][1]+=e[a-1][1][1];for(let c of e[a][2])c[0]+=e[a][1][0],c[1]+=e[a][1][1];for(let c of e[a][3])c[0]+=e[a][1][0],c[1]+=e[a][1][1]}
function La(a){function c(f,m){let n,h=new Fa(f[2],null!=(n=f[3])?n:80,m?0:100*b(),m?Ia:[d(),d(),d(),d()],m?.001:.6*b()+.6,m,a);(h.u=m&&a<=N)&&(h.element.style.filter="hue-rotate(-88deg)");h.position.x=f[0];h.position.y=f[1];H.add(h);return h}Ma(a-3);if(!(a>=e.length||0>a)){var b=u(a),d=()=>[.2*b(),b(),.5*b()+.5],k=0;L=[...L,Ja=c(e[a][1],!0),...e[a][2].map(f=>c(f,!1))];M=[...e[a][3].map(function(f){let m=a%3*2+k++,n=f[0],h=f[1];pa(m,n,h,f[2],f[3]);return[n,h,f[2],a,m]}),...M]}}La(N);La(N-1);
La(N+1);function Ma(a){0>a||(L=L.filter(c=>{let b=c.level===a;b&&H.remove(c);return!b}),M=M.filter(c=>{let b=c[3]===a;b&&pa(c[4],9E9,9E9,0,0);return!b}))}let O=new wa;H.add(O);O.position.x=0;O.position.y=0;let P=L[0],Q=0,Na=0,Oa=0,ba=0,R=new va;H.add(R);let S=2,r=0,t=0,T=Math.atan2(t,r),U=E.position.x,V=E.position.y,W=e[N][0],X=W,Y=!1,Pa=document.getElementById("overlay"),Qa=document.getElementById("boost-bar").style,Ra=document.getElementById("boost-container").style;Ra.width=10*W+"vh";
function Sa(a){X=Math.max(X-a,0);Qa.width=X/W*100+"%"}function Ta(){R.element.style.opacity=1;R.position.x=P.position.x;R.position.y=P.position.y-P.j-.05;R.h=1;E.position.x=U=R.position.x;E.position.y=V=R.position.y;t=r=0;T=Math.atan2(t,r);R.g=T;F=1;Pa.classList.remove("visible");Q=1;S=2;X=W;Sa(0)}let Ua=!1,Z=[];function Va(a,c){Z.push([a,c,!1])}let Wa=0,Xa=0;const I=1/60;
function Ya(a){a/=1E3;var c=a-Wa;Wa=a;c=Math.min(c,.1);Xa+=c;requestAnimationFrame(Ya);for(a=Y;Xa>-I/2;){Xa-=I;Za();for(c=0;c<Z.length;++c){var b=Z[c];b[2]&&b[0]();0>=(b[1]-=I)&&(Z.splice(c,1),--c,b[0]())}Ha=Ga=!1}Y&&(Y=1!==S);a!==Y&&(y.gain.linearRampToValueAtTime(+!Y,v.currentTime),y.gain.linearRampToValueAtTime(+Y,v.currentTime+.1));a=.45/F;c=window.innerWidth/window.innerHeight*a;b=Ja.position.x-E.position.x;const d=Ja.position.y-E.position.y,k=g(d,-a,a);O.position.x=E.position.x+g(b,-c,c);O.position.y=
E.position.y+k;O.g=Math.atan2(d,b);O.element.style.opacity=+(Math.abs(b)>1.5*c||Math.abs(d)>1.5*a);sa()}function $a(a){a>Math.PI?a-=2*Math.PI:a<-Math.PI&&(a+=2*Math.PI);return a}
function ab(){ya(50,{x:R.position.x,y:R.position.y});A(50,.5,v.currentTime,.1,.5,.5,"square");A(70,.5,v.currentTime,.1,.3,.3,"sawtooth");B(.3,v.currentTime,z(),!0,1E3,2,.02,.6,0);S=1;Pa.classList.add("visible");R.element.style.opacity=0;x.gain.linearRampToValueAtTime(0,v.currentTime);x.gain.linearRampToValueAtTime(-20,v.currentTime+.5);Va(()=>{Ta();x.gain.linearRampToValueAtTime(-20,v.currentTime);x.gain.linearRampToValueAtTime(0,v.currentTime+.5)},1)}let bb=!0;
function Za(){Aa();if(!bb&&1!==S){var a=.02*I,c=g(Math.abs(V-R.position.y),0,5)/5;U+=(R.position.x-U)*(g(Math.abs(U-R.position.x),0,5)/5)**1.5;V+=(R.position.y-V)*c**1.5;E.position.x=U;E.position.y=V;F+=.5*(1/(1+.5*da())-F)*I;if(0===S){if(Ha){ab();return}for(var b of L){c=b.position.x-R.position.x;var d=b.position.y-R.position.y,k=c*c+d*d;let f=b.G/k;if(Math.sqrt(k)<b.j+R.j+(b.F&&!b.u?.05:0)){if(b.F&&!b.u){S=2;r=t=0;La(++N+1);window.localStorage.setItem("kimbatt-js13k-2021",N);B(.2,v.currentTime,
z(),!0,1E3,2,.01,.05,.1);A(555,1,v.currentTime,.1,.2,10,"sawtooth");A(66,1,v.currentTime,.1,.2,10,"sawtooth");Y=!1;X=W=e[N][0];Ra.width=10*W+"vh";Sa(0);P=b;b.u=!0;b.element.style.filter="hue-rotate(-88deg)";Q=0;Na=R.position.x;Oa=R.position.y;ba=T;N===e.length-1&&(bb=!0,Va(()=>{document.getElementById("start-text").style.display="none";document.getElementById("game-completed").style.display="";Pa.classList.add("visible")},.5),w.gain.linearRampToValueAtTime(.5,v.currentTime),w.gain.linearRampToValueAtTime(0,
v.currentTime+4));return}ab();return}r+=c*f*a;t+=d*f*a}for(const f of M){b=f[0]-R.position.x;c=f[1]-R.position.y;d=b*b+c*c;k=2E3*f[2]/d;if(Math.sqrt(d)<f[2]+R.j){S=1;Pa.classList.add("visible");let m=0,n=R.position.x,h=R.position.y;Z.push([()=>{m+=I/.3;R.element.style.opacity=R.h=Math.max(0,1-m);R.position.x=n+(f[0]-n)*m;R.position.y=h+(f[1]-h)*m},.3,!0]);x.gain.linearRampToValueAtTime(0,v.currentTime);x.gain.linearRampToValueAtTime(-20,v.currentTime+.5);Va(()=>{Ta();x.gain.linearRampToValueAtTime(-20,
v.currentTime);x.gain.linearRampToValueAtTime(0,v.currentTime+.5)},1);return}r+=b*k*a;t+=c*k*a}if(Y=K&&0<X)b=Math.cos(T),c=Math.sin(T),d=500+-485*g(Math.hypot(r,t)/10,0,1),r+=b*I*d,t+=c*I*d,d=.01*Math.random()+.025,ya(1,{angle:T+(Math.random()-.5),x:R.position.x-.02*b,y:R.position.y-.02*c,speed:5*I,A:d,B:d}),Sa(I);r*=1-5*a;t*=1-5*a;b=Math.hypot(r,t);c=Math.min(25,b);r*=c/b;t*=c/b;R.position.x+=r*a;R.position.y+=t*a;b=$a(Math.atan2(t,r)-T);a*=80;b=g(b,-a,a);T=$a(T+b)}else 2===S&&(a=Math.atan2(R.position.y-
P.position.y,R.position.x-P.position.x)+.15*I/P.j,c=Math.cos(a),b=Math.sin(a),Q=Math.min(Q+I/.5,1),a+=Math.PI/2,c=P.position.x+(P.j+.05)*c,b=P.position.y+(P.j+.05)*b,d=1-(1-Q)**2,T=aa(a,d),R.position.x=Na+(c-Na)*d,R.position.y=Oa+(b-Oa)*d,Ga&&(S=0,r=15*Math.cos(a),t=15*Math.sin(a)));R.g=T}}requestAnimationFrame(Ya);window.addEventListener("resize",()=>sa());window.StartGame=function(){Ua||(Ua=!0,ha(),Ta(),bb=!1)};
